### ISSUE TITLE
2021-06-24/2021-06-25: ISC tutorial

### ISSUE THREAD

**Issue by bernhold** [bssw-tutorial/management#10]
- [x] Finalize agenda and presenters
- [x] Institutional foreign travel requests
  - [x] DavidB
  - [x] Anshu
  - [x] Pat
  - [x] Rinku
  - [x] DavidR
- [x] ECP foreign travel requests
  - [x] DavidB
  - [x] Anshu
  - [x] Pat
  - [x] Rinku
  - [x] DavidR
- [ ] Update all presentations
- [x] Add license slides
- [x] Add agenda slides
- [x] Update Linklings with consent and initial materials, due **2021-06-15** 
  - [x] DavidB
  - [x] Anshu
  - [x] Pat
  - [x] Rinku
  - [x] DavidR
- [ ] Update and publish tutorial web page
- [ ] Generate final PDFs
- [ ] Archive on FigShare

**Comment by bernhold** [comment]
Anshu, Rinku, and Pat have agreed to present.

DavidR can present if needed, but has limited time and is concerned about taking on a significant new time commitment.  Maybe he can assist with hands-on activities instead of presenting?

**Comment by bernhold** [comment]
The latest plan is that we will have fully functioning Zoom sessions for the tutorials.  Breakout rooms will be enabled.  Chat will be enabled.

I've sent all of the volunteers a calendar invite to hold the time blocks.

The organizers want breaks to be synchronized (they will have some kind of mixer activities during them).  So the requested structure is 120 min instruction + 30 min break + 90 min instruction.  Our next step will be to work out the details of the agenda.

**Comment by bernhold** [comment]
### Day 1
| Duration | Seq | Topic | Presenter |
|----------:|-----:|--------|-----------|
| 10 | 00 | Introduction and Setup | David E. Bernholdt, ORNL |
| 20 | 01 | Motivation and Overview of Best Practices in HPC Software Development | David E. Bernholdt, ORNL |
| 30 | 02 | Agile Methodologies | Rinku Gupta, ANL |
| 30 | 03 | Git Workflows | **Rinku or Pat** |
| 30 | 04 | Scientific Software Design | Anshu Dubey, ANL |
| 30 | | *Break* | |
| 30 | 05 | Improving Reproducibility Through Better Software Practices | David E. Bernholdt, ORNL |
| 15 | 06 | Agile Methodologies Redux | Rinku Gupta, ANL |
| 45 | | Hands-On Activities | All |

### Day 2 
| Duration | Seq | Topic | Presenter |
|----------:|-----:|--------|-----------|
| 25 | 07 | Software Testing 1 | David M. Rogers, ORNL |
| 15 | 08 | Software Testing 1a | David M. Rogers, ORNL |
| 20 | 09 | Software Testing 2 | **Patricia A. Grubel, LANL** |
| 30 | 10 | Continuous Integration | **Patricia A. Grubel, LANL** |
| 30 | | Hands-On Activities | All |
| 30 | | *Break* | |
| 45 | 11 | Refactoring Scientific Software | Anshu Dubey, ANL |
| 15 | 12 | Summary | Anshu Dubey, ANL |
| 30 | | Hands-On Activities | All |

**Comment by bernhold** [comment]
Presentation development priorities
* Motivation: Work in <https://bestpractices.coreinfrastructure.org/en>
* Git Workflows: Emphasize more git and git workflows as a collaborative tool
* Testing 1a: Discuss TDD approach, with example
* CI: Update practical examples based on hands-on

**Comment by bernhold** [comment]
Hands-On development suggestions:
* CI: Move from Travis to GHA or another services (CircleCI?)
* CI: Make sure code coverage task actually works (we had problems last time we used it)

**Comment by rinkug** [comment]
> * Git Workflows: Emphasize more git and git workflows as a collaborative tool

Do we need some introductory slides to Git in Git workflows? Some more emphasis and explanations related to how git workflows are defined as "team-accepted high-level patterns/rules on how to use git for efficient collaboration" but the technical concept of git remain the same, independent of git workflows. 

We should narrow down on who is presenting the Workflows slides so that the presenter can work on an initial draft of revisions to suit their comfort level and others can provide feedback.

**Comment by bernhold** [comment]
> Do we need some introductory slides to Git in Git workflows?

My feeling is probably not.  We want to keep the BSSw tutorials focused on things where we can really add value and where CSE/HPC demands a different perspective than general "industrial" computing. There's plenty of material out there on how to use git, at multiple levels.  We might want to mention some of the resources we particularly like for that (and make sure they're in bssw.io), but not try to replicate them. (Ross Bartlett would be a good person to advise on this.)  Further, our informal surveys of our audience suggest that a majority are now already using git, so they're familiar with at least the core ideas/capabilities.

My feeling is that we should talk about pull requests (and mention the idea of peer review and forward reference to CI testing), and branches, and merging but not go into a lot of detail (we can have more detail in the hands-on activities, but we don't want to bog down here in the presentation).  Then we talk about git workflows as a set of rules for how to manage a repository to maintain certain properties (i.e. main is always buildable or deployable or whatever, branches are made for each release and bug fixes may be ported among branches as appropriate, conventions for feature branches, etc.)

However that's just my thinking, and I welcome the opinions of others on this...

**Comment by pagrubel** [comment]
I agree with you David. The main ideas are for how git workflows can help one's project. I think there are those who are using git but might not understand the ideas behind the workflow and handling things like pull requests etc. for the project they may be joining or setting up.

**Comment by bernhold** [comment]
The following issues address the presentation development suggestions:
* All: make sure PPT decks are free of timed slide changes and recorded audio
  - <https://github.com/bssw-tutorial/presentations/issues/12>
* Motivation: Work in https://bestpractices.coreinfrastructure.org/en 
  - <https://github.com/bssw-tutorial/presentations/issues/21>
* Git Workflows: Emphasize more git and git workflows as a collaborative tool
  - <https://github.com/bssw-tutorial/presentations/issues/14>
* Testing 1a: Discuss TDD approach, with example
  - <https://github.com/bssw-tutorial/presentations/issues/22>
* CI: Update practical examples based on hands-on
  - <https://github.com/bssw-tutorial/presentations/issues/23>

**Comment by frobnitzem** [comment]
I've updated [the hands-on material agenda](https://bssw-tutorial.github.io/2021-06-24-isc/2021-06-24-isc) to reflect the agenda above.

I'm currently working to add "solution" branches to the [hands-on matialsi for isc21](https://github.com/bssw-tutorial/hello-numerical-world-isc21).  Those will serve as the basis for building out the "missing" https://bssw-tutorial.github.io/2021-06-24-isc/handson-m08-testing.html, and testing walk-through.  The main challenge is that there are three different repositories to work across - example code, hands-on instructions, and BSSW tutorial presentations (this one).
