### ISSUE TITLE
Hands-On: CI: Move to another CI service

### ISSUE THREAD

**Issue by bernhold** [bssw-tutorial/management#24]
Travis has changed their terms for offer only a minimal free trial.  We would prefer to get people started with a service that it more likely to be of use to them in the longer term. GitHub Automations or CircleCI seem like reasonable candidates and the latest version of the presentation has examples from both.  We need to decide and make sure that the hands-on (code and instructions) and presentation are all consistent.

See also <https://github.com/bssw-tutorial/presentations/issues/23>

**Comment by frobnitzem** [comment]
This has been completed by https://github.com/bssw-tutorial/hello-numerical-world/pull/11.  However, I have not merged that request.  Instead, I created the [workflows](https://github.com/bssw-tutorial/hello-numerical-world-isc21/tree/workflows) branch to capture this step.  It's talked about in the CI presentation, and will be added to the [CI hands-on material](https://bssw-tutorial.github.io/2021-06-24-isc/handson-m10-continuous-integration.html)
