### ISSUE TITLE
2021-04-12: ECP AM tutorial

### ISSUE THREAD

**Issue by bernhold** [bssw-tutorial/management#9]
- [x] Confirm acceptance in Confluence by 2021-02-22
- [x] Finalize title in Confluence by 2021-02-22
- [x] Finalize agenda and presenters
- [x] Provide Tutorial Leader information in Confluence by 2021-02-22
- [x] Notify if Zoom breakout rooms are needed by 2021-03-01
- [x] Ensure all presenters register for ECP AM
- [x] Update presentations by 2021-04-02
- [x] Update hands-on lessons
- [x] Create tutorial web site
- [x] Generate final PDFs by 2021-04-05
- [x] Archive on FigShare
- [x] Provide presentation PDFs in Confluence by 2021-04-05

**Comment by bernhold** [comment]
Agenda and assignments captured at https://docs.google.com/spreadsheets/d/1HLPOEU4DuOFSfunJa4KGe-dk9g1AwmhpsL5YBnaPzoA/edit?usp=sharing (access controlled)

| Sequence |  Lesson Name | Time | Presenter |
|-----------:|-----------------|------:|-----------|
| 0 | Introduction | 5 | DavidB? |
| 1 | Overview | 5 | Pat |
| 2 | Software Testing 1 | 20 | Pat |
| 3 | Software Testing 2 | 25 | DavidB |
| 4 | Continuous Integration | 30 | Jim |
| 5 | Summary | 5 | Jim |

**Comment by jwillenbring** [comment]
I think we can close this one?
